### ISSUE TITLE
Is Possible to set the CustomTabBar as IsVisible = false ?

### ISSUE THREAD

**Issue by Guilherme-Heibel** [VladislavAntonyuk/vladislavantonyuk.github.io#111] opened 2024-08-08 19:16 UTC
Hello!

Currently i'm working with the Shell-TabBar, and im struggling with a issue: https://vladislavantonyuk.github.io/articles/Adding-custom-action-button-to-.NET-MAUI-Shell-TabBar/

It disapear 

I'm trying to hide the central button  when I navigate to a page that doesnt use the TabBar, but the center button stayed visible in every ocasion. you have any suggestions on how to hide the center button?

![Imagem do WhatsApp de 2024-08-08 à(s) 16 16 42_c6be62b5](https://github.com/user-attachments/assets/ae336baa-cb0f-4d87-ac58-ea4a3c7cda95)

**Comment by VladislavAntonyuk** [comment] 2024-08-08 20:02
Duplicate of https://github.com/VladislavAntonyuk/MauiSamples/issues/362

I will take a look later

**Closed by VladislavAntonyuk** 2024-08-08 20:02 UTC
